//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotel.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OTA_HotelResNotifRS xmlns=&quot;http://www.opentravel.org/OTA/2003/05&quot; Version=&quot;{0}&quot; TimeStamp=&quot;{1}&quot; EchoToken=&quot;{2}&quot;&gt;&lt;Errors&gt;{3}&lt;/Errors&gt;&lt;/OTA_HotelResNotifRS&gt;&quot;.
        /// </summary>
        internal static string XmlError {
            get {
                return ResourceManager.GetString("XmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Error Type=&quot;{0}&quot; Code=&quot;{1}&quot;&gt;{2}&lt;/Error&gt;.
        /// </summary>
        internal static string XmlErrorContent {
            get {
                return ResourceManager.GetString("XmlErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;OTA_HotelResNotifRS xmlns=&quot;http://www.opentravel.org/OTA/2003/05&quot; EchoToken=&quot;{0}&quot; TimeStamp=&quot;{1}&quot; Version=&quot;{2}&quot; ResResponseType=&quot;{3}&quot;&gt;
        ///   &lt;Success /&gt;
        ///   &lt;HotelReservations&gt;
        ///     {4}
        ///   &lt;/HotelReservations&gt;
        ///&lt;/OTA_HotelResNotifRS&gt;.
        /// </summary>
        internal static string XmlSuccess {
            get {
                return ResourceManager.GetString("XmlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HotelReservation&gt;
        ///         &lt;UniqueID Type=&quot;{0}&quot; ID=&quot;{1}&quot; /&gt;
        ///         &lt;ResGlobalInfo&gt;
        ///            &lt;HotelReservationIDs&gt;
        ///           {2}
        ///            &lt;/HotelReservationIDs&gt;
        ///         &lt;/ResGlobalInfo&gt;
        ///      &lt;/HotelReservation&gt;.
        /// </summary>
        internal static string XmlSuccessBody {
            get {
                return ResourceManager.GetString("XmlSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HotelReservationID ResID_Type=&quot;{0}&quot; ResID_Value=&quot;{1}&quot; /&gt;.
        /// </summary>
        internal static string XmlSuccessHotelReservation {
            get {
                return ResourceManager.GetString("XmlSuccessHotelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;OTA_HotelResNotifRS xmlns=&quot;http://www.opentravel.org/OTA/2003/05&quot; EchoToken=&quot;{0}&quot; TimeStamp=&quot;{1}&quot; Version=&quot;{2}&quot; ResResponseType=&quot;{3}&quot;&gt;&lt;Success/&gt;&lt;Warnings&gt;{4}&lt;/Warnings&gt;&lt;HotelReservations&gt;{5}&lt;/HotelReservations&gt;&lt;/OTA_HotelResNotifRS&gt;.
        /// </summary>
        internal static string XmlWarning {
            get {
                return ResourceManager.GetString("XmlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Warning Type=&quot;{0}&quot; Code=&quot;{1}&quot; RecordID=&quot;{2}&quot;&gt;{3}&lt;/Warning&gt;.
        /// </summary>
        internal static string XmlWarningContenWarning {
            get {
                return ResourceManager.GetString("XmlWarningContenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HotelReservation&gt;&lt;UniqueID Type=&quot;{0}&quot; ID=&quot;{1}&quot;/&gt;&lt;ResGlobalInfo&gt;&lt;HotelReservationIDs&gt;{2}&lt;/HotelReservationIDs&gt;&lt;/ResGlobalInfo&gt;&lt;/HotelReservation&gt;.
        /// </summary>
        internal static string XmlWarningHotelReservation {
            get {
                return ResourceManager.GetString("XmlWarningHotelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HotelReservationID ResID_Type=&quot;{0}&quot; ResID_Value=&quot;{1}&quot;/&gt;.
        /// </summary>
        internal static string XmlWarningHotelReservationId {
            get {
                return ResourceManager.GetString("XmlWarningHotelReservationId", resourceCulture);
            }
        }
    }
}
