//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.HotelReservationReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelReservationReference.IHotelReservationInterface")]
    public interface IHotelReservationInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelReservationInterface/GetXMLInformation", ReplyAction="http://tempuri.org/IHotelReservationInterface/GetXMLInformationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.OTA_HotelResNotifRQ))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationsTypeHotelReservation[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationsTypeHotelReservation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationTypeBillingInstructionCode[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationTypeBillingInstructionCode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationTypeBillingInstructionCodeResGuestRPH[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationTypeBillingInstructionCodeResGuestRPH))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.SourceType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.SourceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.HotelReservationTypeResGlobalInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.BasicPropertyInfoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ResGuestType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ResGuestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.TransportInfoTypeTransportInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.TransportInfoTypeTransportInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CommentTypeComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CommentTypeComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ParagraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.FormattedTextTextType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.FormattedTextTextType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ResGuestTypeProfileInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ResGuestTypeProfileInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__ProfileType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyInfoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyInfoTypeAddressInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyInfoTypeAddressInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AddressInfoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AddressType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CountryNameType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.StateProvType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyNameType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyNameType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ContactPersonType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ContactPersonType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AddressInfoType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.EmailType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.EmailType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.PersonNameType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ContactPersonTypeTelephone[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ContactPersonTypeTelephone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyInfoTypeEmail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyInfoTypeEmail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyInfoTypeTelephoneInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.CompanyInfoTypeTelephoneInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeAddress[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeAddress))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeCustLoyalty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeCustLoyalty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeEmail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeEmail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.PersonNameType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RelatedTravelerType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RelatedTravelerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.UniqueID_Type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeTelephone[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_ResGuest__CustomerTypeTelephone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.UniqueID_Type[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceRPHsTypeServiceRPH[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceRPHsTypeServiceRPH))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.SpecialRequestTypeSpecialRequest[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.SpecialRequestTypeSpecialRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomStaysTypeRoomStay[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomStaysTypeRoomStay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomStayType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePayment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePayment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AcceptedPaymentsTypeAcceptedPayment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AcceptedPaymentsTypeAcceptedPayment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.PaymentFormType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePaymentAddress[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePaymentAddress))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePaymentAmountPercent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AmountPercentType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.TaxesType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.TaxType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.TaxType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.FormattedTextTextType[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePaymentDeadline[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePaymentDeadline))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.DiscountType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.TotalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.GuaranteeType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.GuaranteeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.GuaranteeTypeGuaranteeAccepted[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.GuaranteeTypeGuaranteeAccepted))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.GuestCountTypeGuestCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.GuestCountTypeGuestCount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RatePlanType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RatePlanType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AdditionalDetailType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.AdditionalDetailType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RatePlanTypeMealsIncluded))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RatePlanInclusionsType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomStayTypeRoomRate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomStayTypeRoomRate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomTypeType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomTypeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RoomStayTypeTimeSpan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.MembershipTypeMembership[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.MembershipTypeMembership))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ResGuestRPHsTypeResGuestRPH[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ResGuestRPHsTypeResGuestRPH))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServicesType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServicesTypeServiceCategory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServicesTypeServiceCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceTypePrice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceTypePrice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceTypeServiceDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.ServiceTypeServiceDetailsTimeSpan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.DataContracts.RESX_HotelReservationType__UniqueID_Type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.Utilities.HotelResStatusType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.Utilities.PaymentFormTypePaymentTransactionTypeCode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.Utilities.RESX_DepositPayments_RequiredPaymentsTypeGuaranteePaymentDeadlineOffsetDropTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.Utilities.TimeUnitType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.Utilities.GuaranteeTypeGuaranteeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.Utilities.PricingType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WcfServiceHotel.Utilities.TransactionStatusType))]
        WcfServiceHotel.DataContracts.OTA_HotelResNotifRS GetXMLInformation(WcfServiceHotel.DataContracts.OTA_HotelResNotifRQ request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelReservationInterface/GetXMLInformation", ReplyAction="http://tempuri.org/IHotelReservationInterface/GetXMLInformationResponse")]
        System.Threading.Tasks.Task<WcfServiceHotel.DataContracts.OTA_HotelResNotifRS> GetXMLInformationAsync(WcfServiceHotel.DataContracts.OTA_HotelResNotifRQ request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelReservationInterfaceChannel : Cliente.HotelReservationReference.IHotelReservationInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelReservationInterfaceClient : System.ServiceModel.ClientBase<Cliente.HotelReservationReference.IHotelReservationInterface>, Cliente.HotelReservationReference.IHotelReservationInterface {
        
        public HotelReservationInterfaceClient() {
        }
        
        public HotelReservationInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelReservationInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelReservationInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelReservationInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceHotel.DataContracts.OTA_HotelResNotifRS GetXMLInformation(WcfServiceHotel.DataContracts.OTA_HotelResNotifRQ request) {
            return base.Channel.GetXMLInformation(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceHotel.DataContracts.OTA_HotelResNotifRS> GetXMLInformationAsync(WcfServiceHotel.DataContracts.OTA_HotelResNotifRQ request) {
            return base.Channel.GetXMLInformationAsync(request);
        }
    }
}
